### ISSUE TITLE
Treffen Nummer Drei (diesmal mit Tutor)

### ISSUE THREAD

**Issue by jakicoll** [ProPra16/programmierpraktikum-abschlussprojekt-gg-ez#1]
@Hunter42 @Alexandros31 @Jon4sW @marcelg1909 

Hallo Liebe Gruppe gg-ez.

Ich würde gerne an eurem dritten wöchentlichen Treffen anfangs kurz teilnehmen, um euch kennenzulernen und den aktuellen Stand zu erfahren.

Die Protokolle zu euren ersten beiden Treffen ~~sind leider ohne Termin~~ (**Termin steht ja doch drauf. Sorry**), so dass ich euch hier einmal die mögliche Zeiten vorschlage, zu denen ich kann:
- Mittwoch ab 13:00 Uhr (14 Uhr wäre auch möglich).
- Donnerstag um 14 Uhr (also nach der ProPra-Vorlesung)
- Freitag zwischen 10:00 Uhr und 12:00 Uhr sowie um 12:30 Uhr.

Bitte gebt mir möglichst bald eine Rückmeldung.

Viele Grüße,

Jakob Scheumann
Korrektor/Tutor Programmierpraktikum

**Comment by Chibi42** [comment]
Treffen 3 ist Donnerstag der 7. Juli um ca. 14:10 am zim(bei den roten Bänken)

**Comment by jakicoll** [comment]
Da finde ich hin. :smirk_cat: 

Bis Donnertag,

Jakob
