### ISSUE TITLE
Frage zur Aufgabenstellung

### ISSUE THREAD

**Issue by ccrijnen** [ProPra16/programmierpraktikum-abschlussprojekt-gg-ez#3]
Hallo,
in der Aufgabenstellung steht, dass es einen Katalog geben soll der mögliche Übungen enthält.
Wir haben jetzt für jede Übung eine eigene Datei und wissen nicht, ob das so in Ordnung ist, wie wir es momentan haben.

Grüße,
Cornelius

**Comment by jakicoll** [comment]
Also wegen mir reicht es so aus. :)

Dann gibt man den Studierenden den Ordner mit allen Übungsdateien und sie laden in eurem Programm jeweils eine Datei.

Grüße,

Jakob
